name: receive_sharing_intent
description: A flutter plugin that enables flutter apps to receive sharing photos, text or url from other apps.
version: 2.0.0
homepage: https://github.com/SunnatilloShavkatov/receive_sharing_intent

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.kasem.receive_sharing_intent
        pluginClass: ReceiveSharingIntentPlugin
      ios:
        pluginClass: ReceiveSharingIntentPlugin
